# Generated by Django 3.1.7 on 2021-03-31 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='news_win_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='partcepant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(blank=True, db_index=True)),
                ('name_tt', models.CharField(max_length=20)),
                ('team_name', models.CharField(default='none', max_length=20)),
                ('leader_dicord_id', models.CharField(default='none', max_length=30)),
                ('le_name', models.CharField(max_length=20)),
                ('leader', models.CharField(max_length=20)),
                ('m1_name', models.CharField(blank=True, max_length=20)),
                ('mem1', models.CharField(blank=True, max_length=20)),
                ('m2_name', models.CharField(blank=True, max_length=20)),
                ('mem2', models.CharField(blank=True, max_length=20)),
                ('m3_name', models.CharField(blank=True, max_length=20)),
                ('mem3', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tonament_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonament_name', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=70)),
                ('solo', models.BooleanField(default=False)),
                ('team', models.BooleanField(default=False)),
                ('pubg', models.BooleanField(default=False)),
                ('free_fire', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='room_pass_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20)),
                ('room_pass', models.CharField(max_length=20)),
                ('competation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.tonament_list')),
            ],
        ),
        migrations.CreateModel(
            name='blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
