# Generated by Django 3.1.7 on 2021-03-31 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='not defined', max_length=50)),
                ('free_fire_ch_box', models.BooleanField(default=False)),
                ('free_fire_us_na', models.CharField(blank=True, max_length=40)),
                ('free_fire_us_id', models.CharField(blank=True, max_length=40)),
                ('pubg_ch_box', models.BooleanField(default=False)),
                ('pubg_us_na', models.CharField(blank=True, max_length=40)),
                ('pubg_us_id', models.CharField(blank=True, max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
